### ISSUE TITLE
ipywidgets.Output() is not displaying in Colab

### ISSUE THREAD

**Issue by mortcanty** [googlecolab/colab-cdn-widget-manager#4]
**This cell generates no output in colab:**

from IPython.display import display, Javascript
import ipywidgets as widgets

display(Javascript('''
  google.colab.widgets.installCustomManager('https://ssl.gstatic.com/colaboratory-static/widgets/colab-cdn-widget-manager/6a14374f468a145a/manager.min.js');
'''))

w_out = widgets.Output(
    layout={'border': '1px solid black'}
)

with w_out:
    print('Hello')

w_out

**Comment by blois** [comment]
Thanks for the report, will have a fix ready shortly.

One thing that I noticed is that the border will have to change to:
```python
w_out = widgets.Output(
  layout=widgets.Layout(border='1px solid black')
)
```

I believe this is a result of https://github.com/jupyter-widgets/ipywidgets/commit/f7036705a80c95f1f72b3bed8d500a9807510d00#diff-06248f0e2056c2e7ba095a015fbc2cbff80157a99a7860395ca51c9eb716bf20.

**Comment by blois** [comment]
Fixed with https://github.com/googlecolab/colab-cdn-widget-manager/pull/6.

**Comment by wattcommunity** [comment]
> It still doesn't work, it displays no text at all.

2024 and still not working. Are we missing something!

My code:
```
import ipywidgets as widgets
out = widgets.Output(layout={'border': '1px solid black'})
# this printing appears below in this cell's output area as expected:
print ("testing")
print (out.get_view_spec())

out
# no idea where this output is going !!!
with out:
    for i in range(10):
        print(i, 'Hello world!')
```

**Comment by wattcommunity** [comment]
> > It still doesn't work, it displays no text at all.
> 
> 2024 and still not working. Are we missing something!
> 
> My code:
> 
> ```
> import ipywidgets as widgets
> out = widgets.Output(layout={'border': '1px solid black'})
> # this printing appears below in this cell's output area as expected:
> print ("testing")
> print (out.get_view_spec())
> 
> out
> # no idea where this output is going !!!
> with out:
>     for i in range(10):
>         print(i, 'Hello world!')
> ```

Yes I was missing something! Like (all?) widgets, you have to display the widget:

```
display(out)
```

Do this in another cell, and anything printed in the with block will go there! Magic.
